RoR Project: Micro-Redddit
EroAuditore/micro_reddit pull request #1
Opened 2021-03-18 21:43 UTC by chuckbuckethead

- Created models and migration files for Post, User, and Comment
- Added validations
- Added associations between the three models (ie, `has_many` to User in relation to Comment, and so on)

2021-03-19 00:51 UTC, LamiaSristy reviewed
# Status: Invalid Review Request ✖️

Hello @chuckbuckethead  and @EroAuditore. I can see a lot of effort and dedication here, but unfortunately, I have to mark this review request as invalid.

## The issue:
**Not Professional PR as Added No custom README.**
There is no custom README added, kindly make sure that your repo looks professional, and a custom README is a must for that. Please take a look at this [template](https://github.com/microverseinc/readme-template).

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

Feel free to reach me on slack @lamiasristy 🙋

Keep up the spirit always. Happy Coding 💻

2021-03-19 19:11 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @chuckbuckethead and @EroAuditore :clap: :clap: 
#### Good job :+1: The models are well implemented.
#### However, some requirements are missing/not implemented correctly. Check my comments below :point_down:

#### 1) Readme:
 - Add instruction on how to run database migration

#### _Reviewed by Temitayo Adeleke_

2021-03-19 19:11 UTC, lekegitrepo commented on README.md
> +- Run `ruby console`
- This should be `rails console`

2021-03-19 19:56 UTC, chuckbuckethead commented on README.md
> +- Run `ruby console`
Done!

2021-03-19 19:56 UTC, chuckbuckethead commented
Added instruction on how to run database migration, per TSE recommendation.

2021-03-20 02:42 UTC, umairarshadbutt reviewed
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @chuckbuckethead and @EroAuditore ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-03-20 20:35 UTC, merged